#!/usr/bin/env php
<?php
    require("../includes/functions.php");
    // Ensure proper usage, that file exists, that file is readable, and that file can be opened.
    if ($argc!=2)
    {
        print("Usage: ./import (path/to/file.txt)\n");
        return -1;
    }
    
    $filename = $argv[1];
    if(!file_exists($filename))
    {
        print("File ".$filename." does not appear to exist\n");
        return -2;
    }
    
    if(!is_readable($filename))
    {
        print("File ".$filename." cannot be read\n");
        return -3;
    }
    
    $file = fopen($filename,'r');
    if(!$file)
    {
        print("File cannot be opened\n");
        return -4;
    }
    // define some constants for each column of phpmyadmin table.
    
    // iterate through file with fgetcsv and put into the table!
    $currentline = 1;
    $filetextcsv = fgetcsv($file,' ');
    $filetext = str_getcsv($filetextcsv[0],' ');
    for ($i = 0, $n = count($filetext); $i<$n; $i++)
    {
        query("INSERT INTO `wordbank` (word) VALUES (?)", $filetext[$i]);
    }
    
    // close file
    fclose($file);    
?>
